In [1]:
# Required Libraries 

%pip install pandas numpy matplotlib seaborn scikit-learn scipy statsmodels jupyter==1.0.0 notebook==7.2.0 ipykernel==6.29.4

Requirement already satisfied: pandas in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.4.4)
Requirement already satisfied: matplotlib in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.8.0)
Requirement already satisfied: scipy in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.17.1)
Requirement already satisfied: statsmodels in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.14.6)
Requirement already satisfied: jupyter==1.0.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.0.0)
Requirement already satisfied: notebook==7.2.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (7.2.0)
Requirement already satisfied: ipykernel==6.29.4 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (6.29.4)
Requirement already satisfied: qtconsole in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter==1.0.0) (5.7.2)
Requirement already satisfied: jupyter-console in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter==1.0.0) (6.6.3)
Requirement already satisfied: nbconvert in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter==1.0.0) (7.17.1)
Requirement already satisfied: ipywidgets in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter==1.0.0) (8.1.8)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from notebook==7.2.0) (2.17.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from notebook==7.2.0) (2.28.0)
Requirement already satisfied: jupyterlab<4.3,>=4.2.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from notebook==7.2.0) (4.2.7)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from notebook==7.2.0) (0.2.4)
Requirement already satisfied: tornado>=6.2.0 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from notebook==7.2.0) (6.5.5)
Requirement already satisfied: comm>=0.1.1 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (9.12.0)
Requirement already satisfied: jupyter-client>=6.1.12 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (8.8.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (0.2.1)
Requirement already satisfied: nest-asyncio in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (1.6.0)
Requirement already satisfied: packaging in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (26.1)
Requirement already satisfied: psutil in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (7.2.2)
Requirement already satisfied: pyzmq>=24 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (27.1.0)
Requirement already satisfied: traitlets>=5.4.0 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipykernel==6.29.4) (5.14.3)
Requirement already satisfied: anyio>=3.1.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (4.13.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (25.1.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (3.1.6)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (5.10.4)
Requirement already satisfied: prometheus-client>=0.9 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (0.25.0)
Requirement already satisfied: pywinpty>=2.0.1 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (3.0.3)
Requirement already satisfied: send2trash>=1.8.2 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.4.0->notebook==7.2.0) (1.9.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook==7.2.0) (2.3.0)
Requirement already satisfied: httpx>=0.25.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook==7.2.0) (0.28.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook==7.2.0) (2.3.1)
Requirement already satisfied: setuptools>=40.8.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook==7.2.0) (82.0.1)
Requirement already satisfied: babel>=2.10 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook==7.2.0) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook==7.2.0) (0.14.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook==7.2.0) (4.26.0)
Requirement already satisfied: requests>=2.31 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook==7.2.0) (2.33.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: idna>=2.8 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (3.13)
Requirement already satisfied: argon2-cffi-bindings in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook==7.2.0) (25.1.0)
Requirement already satisfied: certifi in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook==7.2.0) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook==7.2.0) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook==7.2.0) (0.16.0)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel==6.29.4) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel==6.29.4) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel==6.29.4) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel==6.29.4) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel==6.29.4) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel==6.29.4) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel==6.29.4) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel==6.29.4) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel==6.29.4) (0.8.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook==7.2.0) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook==7.2.0) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook==7.2.0) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook==7.2.0) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook==7.2.0) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel==6.29.4) (4.9.6)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (6.0.3)
Requirement already satisfied: rfc3339-validator in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (0.1.1)
Requirement already satisfied: fqdn in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (1.5.1)
Requirement already satisfied: isoduration in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (1.1.0)
Requirement already satisfied: uri-template in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (25.10.0)
Requirement already satisfied: beautifulsoup4 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter==1.0.0) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter==1.0.0) (6.3.0)
Requirement already satisfied: defusedxml in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter==1.0.0) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter==1.0.0) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter==1.0.0) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter==1.0.0) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter==1.0.0) (1.5.1)
Requirement already satisfied: webencodings in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter==1.0.0) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter==1.0.0) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (2.21.2)
Requirement already satisfied: six>=1.5 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook==7.2.0) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook==7.2.0) (2.6.3)
Requirement already satisfied: lark>=1.2.2 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (1.3.1)
Requirement already satisfied: executing>=1.2.0 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel==6.29.4) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel==6.29.4) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\hemak\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel==6.29.4) (0.2.3)
Requirement already satisfied: cffi>=2.0.0b1 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook==7.2.0) (2.0.0)
Requirement already satisfied: pycparser in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cffi>=2.0.0b1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook==7.2.0) (3.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from beautifulsoup4->nbconvert->jupyter==1.0.0) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from beautifulsoup4->nbconvert->jupyter==1.0.0) (4.15.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipywidgets->jupyter==1.0.0) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipywidgets->jupyter==1.0.0) (3.0.16)
Requirement already satisfied: arrow>=0.15.0 in c:\Users\hemak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook==7.2.0) (1.4.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler # Data preprocessing
from sklearn.model_selection import train_test_split # Data splitting
from sklearn.linear_model import LinearRegression # Machine learning model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score # Model evaluation metrics Validation

In [3]:
df = pd.read_csv('patient_recovery_data.csv')
df.head()

,Age,BMI,Blood_Pressure,Therapy_Hours,Medication_Dosage,Preexisting_Score,Recovery_Days,Pain_Reduction_Score
0,58,35.5,129.0,14.3,76.3,0,67.2,0.0
1,71,19.2,71.0,16.1,76.7,4,44.7,7.7
2,48,39.7,70.0,17.9,14.8,9,77.4,0.0
3,34,34.9,117.0,7.4,90.7,8,98.7,0.0
4,62,22.0,81.0,8.1,53.0,5,64.6,0.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   120 non-null    int64
 1   BMI                   120 non-null    float64
 2   Blood_Pressure        115 non-null    float64
 3   Therapy_Hours         120 non-null    float64
 4   Medication_Dosage     115 non-null    float64
 5   Preexisting_Score     120 non-null    int64
 6   Recovery_Days         120 non-null    float64
 7   Pain_Reduction_Score  120 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 7.6 KB

In [5]:
# Before any data prediction, need to verify whether there is NULL values running the code - df.info()

df.fillna(df.mean(), inplace=True)

,Age,BMI,Blood_Pressure,Therapy_Hours,Medication_Dosage,Preexisting_Score,Recovery_Days,Pain_Reduction_Score
0,58,35.5,129.0,14.3,76.3,0,67.2,0.0
1,71,19.2,71.0,16.1,76.7,4,44.7,7.7
2,48,39.7,70.0,17.9,14.8,9,77.4,0.0
3,34,34.9,117.0,7.4,90.7,8,98.7,0.0
4,62,22.0,81.0,8.1,53.0,5,64.6,0.0
...,...,...,...,...,...,...,...,...
115,79,38.3,105.0,15.8,87.3,9,103.4,0.0
116,79,37.2,114.0,7.5,9.3,1,96.8,0.0
117,64,23.3,89.0,18.7,7.5,0,36.0,11.9
118,60,32.3,134.0,17.3,40.8,9,83.4,0.0
119,48,35.9,77.0,9.2,82.0,8,93.3,0.0

In [6]:
# Describe - find the highest range, lowest range 

df.describe()

,Age,BMI,Blood_Pressure,Therapy_Hours,Medication_Dosage,Preexisting_Score,Recovery_Days,Pain_Reduction_Score
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,50.850000,28.394167,109.730435,10.008333,54.456522,4.033333,69.301667,1.687500
std,17.971336,6.627550,23.099100,5.542693,29.301628,2.936108,19.155055,4.147401
min,21.000000,17.600000,70.000000,1.300000,6.000000,0.000000,20.000000,0.000000
25%,35.750000,22.750000,92.750000,5.000000,32.000000,1.000000,58.150000,0.000000
50%,48.500000,28.650000,107.500000,10.150000,54.900000,4.000000,67.700000,0.000000
75%,66.000000,34.525000,128.250000,14.450000,79.100000,6.000000,83.825000,0.000000
max,79.000000,39.700000,159.000000,19.800000,99.300000,9.000000,113.500000,19.100000

In [7]:
# Finding how many null values

df.isnull().sum()

Age                     0
BMI                     0
Blood_Pressure          0
Therapy_Hours           0
Medication_Dosage       0
Preexisting_Score       0
Recovery_Days           0
Pain_Reduction_Score    0
dtype: int64

In [ ]:
# Visualization the data with Matplotlib
Need to find the target value 


plt.Figure(figsize=(8, 4))
plt.hist(df['Pain_Reduction_Score'], bins=20, edgecolor='k')
plt.title('Distribution of House Prices')
plt.xlabel('Price (USD)')
plt.ylabel('Frequency')
plt.show()

In [9]:
# Going to split the data, Finding the input features and output features 
# updating the i/p and o/p 

features = ['Age', 'BMI', 'Blood_Pressure', 'Therapy_Hours', 'Medication_Dosage', 'Preexisting_Score', 'Recovery_Days']
X = df[features]
y = df['Pain_Reduction_Score']

In [10]:
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=65)

In [11]:
X.head()

,Age,BMI,Blood_Pressure,Therapy_Hours,Medication_Dosage,Preexisting_Score,Recovery_Days
0,58,35.5,129.0,14.3,76.3,0,67.2
1,71,19.2,71.0,16.1,76.7,4,44.7
2,48,39.7,70.0,17.9,14.8,9,77.4
3,34,34.9,117.0,7.4,90.7,8,98.7
4,62,22.0,81.0,8.1,53.0,5,64.6